### ISSUE TITLE
视频文件太大了。一直下不下来--

### ISSUE THREAD

**Issue by WuHanMuMu** [derek-zhang123/MxOnline#1]
能不能搞个小店的视频文件

**Comment by derek-zhang123** [comment]
里面没有视频文件

**Comment by derek-zhang123** [comment]
谢谢提醒 刚删除了

**Comment by 4thefamilyocky** [comment]
视频是上传的还是通过链接去播放的？提示‘NoReverseMatch at /course/video/5/
Reverse for 'list' not found. 'list' is not a valid view function or pattern name.’

**Comment by WuHanMuMu** [comment]
上传的啊

**Comment by derek-zhang123** [comment]
里面没有视频
